apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-web
  name: my-web
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      run: my-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: my-web
    spec:
      containers:
      - image: hoeghh/multitool:v1
        name: my-web
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
