apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-web
  name: my-web
  namespace: default
spec:
  ports:
  - nodePort: 32426
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-web
  sessionAffinity: None
  type: NodePort

